### PR TITLE
Adding an empty alt attribute for accessibility validation

### PR DESCRIPTION
**Pull request by adevendorf**
Accessibility validation tools will report an error because the zoomed image created does not contain a required alt attribute. I've set it to an empty string.

### CODE REVIEW

**Comment by jackmoore** [comment]
Looks good to me, thanks!

**Comment by odahcam** [comment]
Just use a `role="presentation"`attribute. Presentation images has no need of an `alt` attribute.

A blank alt is not good for acessibility, is just more junk code.

```html
<img src="[src]" role="presentation"><!-- valid code -->
```

**Comment by jackmoore** [comment]
@odahcam Sounds good, thanks

**Comment by huguestennier** [comment]
Actually, an empty alt text is the [recommend way](https://www.w3.org/TR/WCAG20-TECHS/H67.html) for ATs to ignore them. Having no `alt` is also not valid HTML.

**Pull request merged**
